name: Build Angular App
 
on:
  push:
    branches:
      - main  # You can change this to your default branch if different
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you want
 
      - name: Install dependencies
        run: npm install
        working-directory: my-angular-app  # Set the working directory to the Angular app folder
 
      - name: Build the Angular app
        run: npm run build
        working-directory: my-angular-app  # Build the Angular app
